### ISSUE TITLE
Input data: Cartesian coordinates (in pixels) or Visual Angle degrees?

### ISSUE THREAD

**Issue by pdmadeira** [psychoinformatics-de/remodnav#25]
As discussed previously by email, I was wondering if the input data (x- and y- positions) has to be in pixel coordinates or if it could be in visual degrees. I've been using the algorithm and came into an interesting scenario: 

- Comparing the algorithm results (default hyperparameters) when inputting data as **visual degrees** vs **pixels**, the first approach seems to more effective (see example pictures below), although the algorithm is designed to receive the values ​​in pixel coordinates

**_Note:_** My dataset is already in visual degrees (returned that way by the MonkeyLogic software), so to convert it to pixels I multiplied the x- and y- values for a converting factor 'PixelsPerDegree' (20.09), also returned by the software. I used the inverse value for the 'px2deg' conversion factor required by the REMoDNaV algorithm (1/20.09), which is very identical to the result of the calculation you suggest in the documentation. 

![image](https://user-images.githubusercontent.com/74116819/117022623-4a15c000-acf0-11eb-94a0-55444a965b5b.png)
![image](https://user-images.githubusercontent.com/74116819/117022857-7df0e580-acf0-11eb-89c2-617fa442f44c.png)

The eye-tracking data is related to a static task. 

Am I interpreting the results well when I conclude that they are more assertive for visual angles as input data? 
I emphasize once again that I am using hyperparameters' default values.

Thanks in advance for the help!

**Comment by adswa** [comment]
mhh, that's an interesting question. @mih, do you have thoughts on this?

**Comment by bjbraun** [comment]
I observe the same effect in my data where I have as an input the spherical coordinates as elevation and azimuth (similar to the visual angles).

The saccade are both the same because they use the same velocities, only the intersaccade periods are differently labeled as fixations/ pursuits.
I think the difference comes from the applied butter lowpass filter. The pixel coordinates/ angles are filtered in the function _fix_or_pursuit in the clf.py file before the velocities are calculated again. Therefore, I think the variable lowpass_cutoff_freq would need to be changed. 

I do however not know how it should be changed. Do you have any thoughts on that?
It should probably depend on the magnitude of the x,y inputs as the pixel coordinates are a lot bigger than the visual angles.

**Comment by bjbraun** [comment]
I think that this comes from the fact that the speed in the algorithm is calculated via sqrt(delta_x^2 + delta_y^2). In the case where the input is the visual angle, the calculated speeds are a lot smaller because the angles are significantly smaller than the pixel coordinates.

In your case it seems like it works better but I do not think that this is generally the case. 
You would probably achieve similar results with the px input if you increase the parameter pursuit_velthresh.

**Comment by bjbraun** [comment]
@pdmadeira good to hear! In which literatures did you find a value of 30 deg/sec? 

Unfortunately, I do not know how to avoid the problems with blinks either.

**Comment by pdmadeira** [comment]
@bjbraun thanks for your continuous feedback! I'm still expecting someone to be able to help with the blinks issue :)

I made the 30 deg/sec choice for _pursuit_velthresh_ based on the articles below:
[](https://doi.org/10.1109/ACCESS.2017.2735633)
[](https://doi.org/10.1016/0042-6989(85)90160-9)
[](https://doi.org/10.3389/fnsys.2018.00015)

**Comment by bjbraun** [comment]
@pdmadeira Great, thanks a lot!

**Comment by adswa** [comment]
Closing this question-type issue, as I believe others have given informative answers. Please reopen if I am mistaken, and thanks for everyone chiming in. :)
