### ISSUE TITLE
Eye-Gaze data is already in Degrees.

### ISSUE THREAD

**Issue by AlfredLTennyson** [psychoinformatics-de/remodnav#45]
https://github.com/psychoinformatics-de/remodnav/issues/44

Hello.
Thanks a ton and apologies for the late response.
I used %%shell in colab and i think it did work.
`%%shell remodnav "T_Trial1.tsv" \ "remo_out" 1.0 1000.0`

But, now i am getting a weird error .

`Traceback (most recent call last): File "/usr/local/bin/remodnav", line 8, in <module> sys.exit(main()) File "/usr/local/lib/python3.7/dist-packages/remodnav/__init__.py", line 148, in main 'min_blink_duration', 'dilate_nan', 'median_filter_length', File "/usr/local/lib/python3.7/dist-packages/remodnav/clf.py", line 855, in preproc data['x'][mask] = np.nan ValueError: cannot convert float NaN to integer`

Though I did look at the previous query of the same sort,but i am not able to implement it as my gaze data is already in degrees.

**Comment by AlfredLTennyson** [comment]
https://github.com/AlfredLTennyson/eye_gaze_data_for_1_trial/blob/main/T_Trial1.tsv

here is the data file.
Thanks a ton in advance.

**Comment by adswa** [comment]
Thanks for attaching a sample file and the exact command and traceback! I only glanced at the file, but the last 8000 samples of the ~12000 samples in total seem to be all empty. Before diving deeper into this I wanted to ask if this valid, or an artifact of some sort?

**Comment by AlfredLTennyson** [comment]
It is normal because the participant finished the task early. 
You can remove them.
Thanks a ton again.

**Comment by AlfredLTennyson** [comment]
I would like to mention that participants were told to make saccades away from the screen. 
Attaching the graphs of eyeX vs eyeY for 10 such trials. Those large saccades to the upper left corner are the ones that were made outside of the screen.

![image](https://user-images.githubusercontent.com/114279791/195894341-b4398fb0-6d6f-4c9c-83da-92341e678a8a.png)

**Comment by AlfredLTennyson** [comment]
Also the velocities (for eyeX) are plotted below in (degrees/sec). There are large peaks which seem to be blinks but arent. I did not find the missing dots in that time frame. 
![image](https://user-images.githubusercontent.com/114279791/195895337-3f37a207-8d25-4187-8776-f4b5893c514b.png)
Just mentioning,becoz i think your algorithm will definitely remove it.

**Comment by AlfredLTennyson** [comment]
Please do click on the graphs to see the units of x and y axis.

**Comment by AlfredLTennyson** [comment]
I have attached the above images so that you get the feel of what kind of data mine is.

**Comment by AlfredLTennyson** [comment]
And stimuli were static.

**Comment by AlfredLTennyson** [comment]
This is the eyeX plot vs time. 
![image](https://user-images.githubusercontent.com/114279791/195903471-dde56728-f6a4-40a0-901e-4de6009c6479.png)

**Comment by AlfredLTennyson** [comment]
https://github.com/AlfredLTennyson/eye_gaze_data_for_1_trial/blob/main/Untitled8.ipynb
This is the google colab file, in which i have implemented simple I-VT algorithm. 
The results are wrong.

**Comment by AlfredLTennyson** [comment]
Hello! hope everything is fine.
Is my problem solvable?

**Comment by adswa** [comment]
> Hello! hope everything is fine.
Is my problem solvable?

Hey! As GitHub tells me that this is your first set of issues ever I wanted to take a minute to point something out that may not be obvious. Software maintenance is very often, also here, essentially volunteer time that people need to squeeze in between their regular full-time job, looming deadlines, private life, etc. I can see how you need the problem solved, and its certainly absolutely okay to ping people for updates after a certain while, but there for sure will be people out there who could feel like being stepped on their toes - consider that its a weekend and also still a pandemic which in so many cases doubled peoples private care work (or also frequently just knocks people out sick for a while) before pinging. :) 

That being said, I looked into it, and I think the issue is just an extra column and row in your data. remodnav reads in the first and second column as x and y, but your files' first column
seems to be an index (0, 1, 2, 3, ...) and there also is the ``'0' '1' `` header in the first row. If you reformat your file to look like this, things run smoothly: https://gist.github.com/adswa/81cbdbdd4f635c22384c3748b4b5d34a#file-t_trial1-tsv

This is the classification result I'm seeing: 
![Screenshot from 2022-10-16 13-35-11](https://user-images.githubusercontent.com/29738718/196033511-ea6a5545-ae41-47cd-8d6d-67c19c23724e.png)

**Comment by AlfredLTennyson** [comment]
I apologize for being incessant.  I did not take into consideration your point of view. 
Please take care.  Again really sorry.
May i ask just to be sure that you just fed the modified data into the command line call of remodnav without tweaking the px2deg hyper-parameter?
Please take your time. I apologize again for the trouble. And i am grateful for your help.
Happy weekend. 
Thanks and sorry again.

**Comment by AlfredLTennyson** [comment]
![image](https://user-images.githubusercontent.com/114279791/196038429-675a5f43-e149-4a00-97a7-5053b3e0b9f2.png)

Thanks a ton. I got the same result as yours. 
I am grateful. 
Please Take care. 
Enjoy the weekend.
:)
