### ISSUE TITLE
Increase precision of output data

### ISSUE THREAD

**Issue by emilykjensen** [psychoinformatics-de/remodnav#47]
In the `clf.py` file for the function `events2bids_events_tsv()`, the start/end x/y positions are only recorded with 1 decimal point which isn't enough precision for some analyses. 

Is there a reason it is limited to this precision? 
Is there a way to change the precision of the events output file without changing the source code of the library manually?

**Comment by adswa** [comment]
Hi @emilykjensen, its been a while since this was written, but I can't recall any specific reason. Which precision would your usecase need?
There is no switch to influence this from the outside.
But if @mih does not recall or know any specific reason against it, I'd be happy to increase it and make a new release.

**Comment by emilykjensen** [comment]
Thanks @adswa ! I modified the code locally on my machine to save everything at 5 decimals and it seems sufficient for our purposes.

**Comment by adswa** [comment]
Gotcha. I'll give @mih a few days to find this and potentially object. Please ping me in case this gets lost and I haven't been back in touch here by the end of next week. :)

**Comment by adswa** [comment]
I have made a release, it is available from PyPi via pip: https://pypi.org/project/remodnav/1.1.2/. Hope that helps :)

**Comment by emilykjensen** [comment]
Thank you!
